language: ruby

rvm:
  - 1.9.3

before_install:
  - git submodule update --init --recursive
  - sudo ./bin/init

script:
  - export rvmsudo_secure_path=1
  - which bundle
  - rvmsudo gem install bundler -v 1.5.2
  - rvmsudo which bundle
  - rvmsudo ruby --version
  - rvmsudo gem list
  - rvmsudo gem --version
  - rvmsudo bundle --version
  - rvmsudo gem install bundle
  - rvmsudo bundle exec rspec spec
