language: ruby

rvm:
  - 1.9.3

before_install:
  - git submodule update --init --recursive
  - sudo ./bin/init

script:
  - export rvmsudo_secure_path=1
  - rvmsudo ruby --version
  - rvmsudo gem --version
  - rvmsudo bundle --version
  - rvmsudo -E bundle exec rspec spec
